media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: Articles
    type: collection
    path: content/posts
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: SEO Description
        type: text
      - name: date
        label: Publication Date
        type: date
      - name: category
        label: Category
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: featured_image
        label: Featured Image
        type: image
        required: false
      - name: body
        label: Article
        type: rich-text
